title: # Expert Cashew Grafts - Yadukumar Kolathaya 
email: # nyadukumar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Yashaswi Nursery. Here you can find premium grafts of Cashew, Vanilla, Pepper, Mango, Jackfruit, Arecanut.
#  Write an awesome description for your new site here. You can edit this
permalink: ':title/'
baseurl: "/ynursery" # the subpath of your site, e.g. /blog
url: "http://ynursery.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Yashaswi Nursery # add your name
author-pic: yashaswi2.png
about-author: # Yashaswi Nursery is located within the lush greens of Western Ghats, about 50 km from the coastal town of Mangalore. Contact us if you are looking for premium grafts of Cashew, Pepper, Coconut, Jackfruit, Arecanut. 
email: (n yadukumar) at gmail dot com # 
phone: 
website: shishirny.com # Add your website, do not add http://
linkedin: shishirny # Add your Linkedin handle
github: shishirny # Add your Github handle
twitter: '@shishirny' # Add your Twitter handle
instagram:  # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
# discus_identifier: # mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
destination: ./docs/
plugins:
#  - jekyll-paginate
#  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
